name: sales_agent
version: "1.0.0"
config-version: 2

profile: sales_agent

model-paths: ["models"]
seed-paths: ["../data/seed"]

models:
  sales_agent:
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  sales_agent:
    +schema: raw
    +quote_columns: false
